### ISSUE TITLE
Cannot open Jar file

### ISSUE THREAD

**Issue by MohaimenH** [Carusoni-Marco-216558074/2311Venn#8]
Even though I have the up-to-date versions of JDK & JavaFX, the program does not run for me. See the screenshot below.

![image](https://user-images.githubusercontent.com/46415046/76562270-6e269a00-647b-11ea-834f-db1e2db38220.png)

**Comment by prashanth1109** [comment]
upload the project file to eclipse and start from there
you have to add missing javafx files

**Comment by MohaimenH** [comment]
I tried running it on Eclipse, but the project has an error.

**Comment by prashanth1109** [comment]
you have to add missing jar files to the project I got that error too 
when you right-click the project --> build path --> configure build path then you can see the missing jar files with close mark. remove all and add those again as external jar files 

https://gofile.io/?c=JymsrI

**Comment by MohaimenH** [comment]
I have tried it, but it does not work.

![image](https://user-images.githubusercontent.com/46415046/76596116-b7a2d380-64d3-11ea-817d-48640b92e3ce.png)

**Comment by MohaimenH** [comment]
Used the Lab PC (Windows mode) and added the libraries to project again to make it work.

The JAR/project does not work on Linux systems. I will open another issue for that.
